# Generated by Django 3.2.19 on 2023-06-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
                ('course', models.CharField(default='', max_length=200)),
                ('std_type', models.CharField(default='', max_length=200)),
                ('logintime', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
