# Generated by Django 3.2.19 on 2023-06-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizappp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=500)),
                ('opt1', models.CharField(default='', max_length=200)),
                ('opt2', models.CharField(default='', max_length=200)),
                ('opt3', models.CharField(default='', max_length=200)),
                ('opt4', models.CharField(default='', max_length=200)),
                ('ans', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
