# Generated by Django 3.2.19 on 2023-07-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizappp', '0002_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='username',
            field=models.CharField(blank=True, default='1', max_length=200, null=True),
        ),
    ]
