# Generated by Django 3.2.19 on 2023-07-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizappp', '0003_alter_user_register_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='std_type',
            field=models.CharField(blank=True, default='1', max_length=200, null=True),
        ),
    ]
