# Generated by Django 3.2.19 on 2023-07-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizappp', '0004_alter_user_register_std_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='std_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
