# Generated by Django 3.2.19 on 2023-07-22 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizappp', '0005_auto_20230704_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_score', models.IntegerField(default=0)),
                ('quiz_percent', models.IntegerField(default=0)),
                ('quiz_cottect', models.IntegerField(default=0)),
                ('quiz_wrong', models.IntegerField(default=0)),
                ('quiz_total', models.IntegerField(default=0)),
                ('quiz_date', models.CharField(default='', max_length=200)),
                ('quiz_time', models.CharField(default='', max_length=200)),
                ('quiz_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizappp.user_register')),
            ],
        ),
    ]
